const { SlashCommandBuilder } = require('@discordjs/builders')

module.exports = {
	data: new SlashCommandBuilder()
		.setName('production')
		.setDescription('Production log.')
		.addSubcommand(subcommand =>
			subcommand
				.setName('menu')
				.setDescription('Initialize a production log menu.')
				.addStringOption(option =>
					option
						.setName('message-id')
						.setDescription('The message ID of the message whose content will be copied.')
					)
				.addBooleanOption(option => 
					option
						.setName('use-existing')
						.setDescription('Use an existing webhook generated by the bot. Defaults to false.')
						.setRequired(false)
				))
		.addSubcommand(subcommand =>
			subcommand
				.setName('new')
				.setDescription('Adds a new entry to the logistics production log.')
				.addStringOption(option =>
					option.setName('type')
						.setDescription('The type of production log being added.')
						.setRequired(false)
						.addChoices(
							{ name: 'submit', value: 'submit' },
							{ name: 'transfer', value: 'transfer' }
						)
				))
		.addSubcommand(subcommand =>
			subcommand
				.setName('log')
				.setDescription('Sets the channel where all future production logs will be displayed.')
				.addChannelOption(option =>
					option.setName('channel')
						.setDescription('The production log channel.')
						.setRequired(true)
				)),

	async execute(interaction) {
		switch(interaction.options.getSubcommand()) {
			case 'menu':
				return await require('./production/menu').execute(interaction)
			case 'new':
				return await require('./production/new').execute(interaction)
			case 'log':
				return await require('./production/log').execute(interaction)
		}
	},
};