const { SlashCommandBuilder } = require('@discordjs/builders')

module.exports = {
	data: new SlashCommandBuilder()
		.setName('production')
		.setDescription('Production log.')
		.addSubcommand(subcommand =>
			subcommand
				.setName('init')
				.setDescription('Initialize a production log menu.')
				.addStringOption(option =>
					option
						.setName('message-id')
						.setDescription('The message ID of the message whose content will be copied.')
					)
				.addBooleanOption(option => 
					option
						.setName('use-existing')
						.setDescription('Use an existing webhook generated by the bot. Defaults to false.')
						.setRequired(false)
				))
		.addSubcommand(subcommand =>
			subcommand
				.setName('sheet')
				.setDescription('Link the bot to a new google sheet.')
				.addStringOption(option => 
					option
						.setName('id')
						.setDescription('The ID of the Google Sheet that the bot will interface with.')
						.setRequired(true)
				))
		.addSubcommand(subcommand =>
			subcommand
				.setName('new')
				.setDescription('Adds a new entry to the logistics production log.')
				.addStringOption(option =>
					option.setName('type')
						.setDescription('The type of production log being added.')
						.setRequired(false)
						.addChoices(
							{ name: 'submit', value: 'submit' },
							{ name: 'transfer', value: 'transfer' }
						))),

	async execute(interaction) {
		switch(interaction.options.getSubcommand()) {
			case 'init':
				await require('./production/init').execute(interaction)
				break
			case 'sheet':
				const ids = interaction.options.getString('id')
				await interaction.reply(`<@${interaction.user.id}> has linked the Cerebrate to the following Google Sheet: ${ids}`)
				break
			case 'new':
				await require('./production/new').execute(interaction)
				break
		}
	},
};